# 站点基础信息
theme: minima


title: haukaijian's Digital Garden
email: 1394891389@qq.com
description: >- 
  学无止境 | Learning never exhausts the mind.
  记录技术探索与思考的个人空间。

# 作者信息
author:
  name: haukaijian
  email: 1394891389@qq.com




